# consumers/Dockerfile.storage
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY storage_consumer.py .

CMD ["python", "storage_consumer.py"]